/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ProdutoController;
import java.math.BigInteger;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.ModelProduto;
import util.Formatador;

/**
 *
 * @author Vitor
 */
public class ViewProduto extends javax.swing.JFrame {

    ArrayList<ModelProduto> listaModelProdutos = new ArrayList<>();
    ProdutoController produtoController = new ProdutoController();
    ModelProduto modelProduto = new ModelProduto();
    Formatador formatador = new Formatador();
    String salvarAlterar;

    /**
     * Creates new form ViewProduto
     */
    public ViewProduto() {
        initComponents();
        this.carregarProdutos();
        setLocationRelativeTo(null);
        this.habilitarDesabilitarCampos(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtEstoquePro = new javax.swing.JFormattedTextField();
        btnNovoPro = new javax.swing.JButton();
        btnCancelPro = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnEditarPro = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnSalvarPro = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnExcluirPro = new javax.swing.JButton();
        txtPesquisarPro = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPro = new javax.swing.JTable();
        txtCodPro = new javax.swing.JTextField();
        txtNamePro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtValorPro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCodBarra = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VPSoft - Estoque");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        txtEstoquePro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        btnNovoPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/new.png"))); // NOI18N
        btnNovoPro.setText("Novo");
        btnNovoPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoProActionPerformed(evt);
            }
        });

        btnCancelPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/cancel.png"))); // NOI18N
        btnCancelPro.setText("Resetar");
        btnCancelPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelProActionPerformed(evt);
            }
        });

        jLabel4.setText("Quantidade*:");

        btnEditarPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/editar.png"))); // NOI18N
        btnEditarPro.setText("Editar");
        btnEditarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProActionPerformed(evt);
            }
        });

        jLabel3.setText("Preço*:");

        btnSalvarPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/save.png"))); // NOI18N
        btnSalvarPro.setText("Salvar");
        btnSalvarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarProActionPerformed(evt);
            }
        });

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/searcher.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        jLabel2.setText("Produto*:");

        jLabel1.setText("Código:");

        jLabel5.setText("Pesquisar:");

        btnExcluirPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/delete.png"))); // NOI18N
        btnExcluirPro.setText("Excluir");
        btnExcluirPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirProActionPerformed(evt);
            }
        });

        tbPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Produto", "Preço", "Qtd.", "Cod. Barra"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbPro);
        if (tbPro.getColumnModel().getColumnCount() > 0) {
            tbPro.getColumnModel().getColumn(0).setPreferredWidth(20);
            tbPro.getColumnModel().getColumn(1).setPreferredWidth(120);
            tbPro.getColumnModel().getColumn(3).setPreferredWidth(40);
            tbPro.getColumnModel().getColumn(4).setPreferredWidth(100);
        }

        txtCodPro.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel6.setText("Campos marcados com * são obrigatórios.");

        jLabel8.setText("Cod. Barra:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addComponent(txtPesquisarPro, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNovoPro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarPro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirPro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelPro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvarPro))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(17, 17, 17)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCodPro, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(txtNamePro))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValorPro, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEstoquePro)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(221, 221, 221))
                            .addComponent(txtCodBarra))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstoquePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisarPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoPro)
                    .addComponent(btnEditarPro)
                    .addComponent(btnExcluirPro)
                    .addComponent(btnCancelPro)
                    .addComponent(btnSalvarPro))
                .addGap(18, 18, 18)
                .addComponent(jLabel6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProActionPerformed
        // TODO add your handling code here:
        this.salvarAlterar = "editar";
        this.habilitarDesabilitarCampos(true);
        int linha = this.tbPro.getSelectedRow();

        try {
            int codProduto = (int) this.tbPro.getValueAt(linha, 0);
            this.modelProduto = this.produtoController.retornaProdutoController(codProduto);
            this.txtCodPro.setText(String.valueOf(this.modelProduto.getId()));
            this.txtNamePro.setText(this.modelProduto.getName());
            this.txtValorPro.setText(String.valueOf(this.modelProduto.getPrice()).format("%.2f", this.modelProduto.getPrice()));
            this.txtEstoquePro.setText(String.valueOf(this.modelProduto.getEstoque()));
            this.txtCodBarra.setText(String.valueOf(this.modelProduto.getCodBarra()));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Código inválido ou nenhum registro selecionado.", "ERRO", JOptionPane.ERROR_MESSAGE);
            this.habilitarDesabilitarCampos(false);
        }
    }//GEN-LAST:event_btnEditarProActionPerformed

    private void salvarProduto() {
        try {
            this.modelProduto.setName(this.txtNamePro.getText().toUpperCase());
            this.modelProduto.setEstoque(Integer.parseInt(this.txtEstoquePro.getText()));
            this.modelProduto.setPrice(Double.parseDouble(String.valueOf(this.txtValorPro.getText()).replaceAll(",", "")));
            this.modelProduto.setCodBarra(this.txtCodBarra.getText());
            if (this.produtoController.salvarProdutoController(this.modelProduto) > 0) {
                JOptionPane.showMessageDialog(this, "Produto cadastrado com sucesso!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                this.carregarProdutos();
                this.limparCampos();
            } else {
                JOptionPane.showMessageDialog(this, "Falha ao cadastrar o produto!", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Falha ao cadastrar o produto!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void alterarProduto() {
        this.modelProduto.setName(this.txtNamePro.getText());
        this.modelProduto.setEstoque(Integer.parseInt(this.txtEstoquePro.getText()));
        this.modelProduto.setPrice(this.formatador.converteVirgulaParaPonto(this.txtValorPro.getText()));
        this.modelProduto.setCodBarra(this.txtCodBarra.getText());
        if (this.produtoController.alterarProdutoController(this.modelProduto)) {
            JOptionPane.showMessageDialog(this, "Produto atualizado com sucesso!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
            this.carregarProdutos();
            this.limparCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Falha ao atualizar o produto!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void btnCancelProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelProActionPerformed
        // TODO add your handling code here:
        this.habilitarDesabilitarCampos(false);
        this.limparCampos();
    }//GEN-LAST:event_btnCancelProActionPerformed

    private void btnSalvarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarProActionPerformed
        if (this.salvarAlterar.equals("salvar")) {
            this.salvarProduto();
        } else if (this.salvarAlterar.equals("editar")) {
            this.alterarProduto();
        }
    }//GEN-LAST:event_btnSalvarProActionPerformed

    private void btnExcluirProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirProActionPerformed
        // TODO add your handling code here:
        int linha = this.tbPro.getSelectedRow();
        try {
            int codProduto = (int) this.tbPro.getValueAt(linha, 0);
            int result = JOptionPane.showConfirmDialog(this, "Tem certeza que dejesa excluir?", "ATENÇÃO", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (result == JOptionPane.YES_OPTION) {
                if (this.produtoController.excluirProdutoController(codProduto)) {
                    JOptionPane.showMessageDialog(this, "Produto excluido com sucesso!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                    this.carregarProdutos();
                    this.limparCampos();
                    this.habilitarDesabilitarCampos(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Falha ao excluir o produto!", "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Código inválido ou nenhum registro selecionado.", "ERRO", JOptionPane.ERROR_MESSAGE);
            this.habilitarDesabilitarCampos(false);
        }

    }//GEN-LAST:event_btnExcluirProActionPerformed

    private void btnNovoProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoProActionPerformed
        // TODO add your handling code here:
        this.habilitarDesabilitarCampos(true);
        this.salvarAlterar = "salvar";
    }//GEN-LAST:event_btnNovoProActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) this.tbPro.getModel();
        final TableRowSorter<TableModel> classificador = new TableRowSorter<>(modelo);
        this.tbPro.setRowSorter(classificador);
        String texto = this.txtPesquisarPro.getText().toUpperCase();

        classificador.setRowFilter(RowFilter.regexFilter(texto, 1));
    }//GEN-LAST:event_btnPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewProduto().setVisible(true);
            }
        });
    }

    private void habilitarDesabilitarCampos(boolean condicao) {
        this.txtNamePro.setEnabled(condicao);
        this.txtValorPro.setEnabled(condicao);
        this.txtEstoquePro.setEnabled(condicao);
        this.btnSalvarPro.setEnabled(condicao);
        this.txtCodBarra.setEnabled(condicao);
    }

    private void limparCampos() {
        this.txtCodPro.setText("");
        this.txtNamePro.setText("");
        this.txtValorPro.setText("");
        this.txtEstoquePro.setText("");
        this.txtCodBarra.setText("");
    }

    private void carregarProdutos() {
        this.listaModelProdutos = this.produtoController.retornaListaProdutoController();
        DefaultTableModel modelo = (DefaultTableModel) this.tbPro.getModel();
        modelo.setNumRows(0);

        int cont = listaModelProdutos.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                this.listaModelProdutos.get(i).getId(),
                this.listaModelProdutos.get(i).getName(),
                this.listaModelProdutos.get(i).getPrice(),
                this.listaModelProdutos.get(i).getEstoque(),
                this.listaModelProdutos.get(i).getCodBarra()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelPro;
    private javax.swing.JButton btnEditarPro;
    private javax.swing.JButton btnExcluirPro;
    private javax.swing.JButton btnNovoPro;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvarPro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbPro;
    private javax.swing.JTextField txtCodBarra;
    private javax.swing.JTextField txtCodPro;
    private javax.swing.JFormattedTextField txtEstoquePro;
    private javax.swing.JTextField txtNamePro;
    private javax.swing.JTextField txtPesquisarPro;
    private javax.swing.JTextField txtValorPro;
    // End of variables declaration//GEN-END:variables
}
