/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerUser;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelUser;

/**
 *
 * @author Vitor
 */
public class ViewUser extends javax.swing.JFrame {

    ControllerUser controllerUsuario = new ControllerUser();
    ModelUser modelUsuario = new ModelUser();
    ArrayList<ModelUser> listaModelUsuario = new ArrayList<>();
    String salvarAlterar;

    /**
     * Creates new form ViewUser
     */
    public ViewUser() {
        initComponents();
        setLocationRelativeTo(null);
        this.carregarUsuarios();
        this.habilitarDesabilitarCampo(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodUser = new javax.swing.JTextField();
        txtNameUser = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUser = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnNovoUser = new javax.swing.JButton();
        btnEditarUser = new javax.swing.JButton();
        btnExcluirUser = new javax.swing.JButton();
        btnCancelarUser = new javax.swing.JButton();
        btnSalvarUser = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VPSoft - Usuário");
        setResizable(false);

        jLabel1.setText("Código:");

        jLabel2.setText("Usuário*:");

        txtCodUser.setEnabled(false);

        tbUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Usuário", "Login"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbUser);
        if (tbUser.getColumnModel().getColumnCount() > 0) {
            tbUser.getColumnModel().getColumn(0).setMaxWidth(70);
            tbUser.getColumnModel().getColumn(1).setMinWidth(300);
        }

        jLabel3.setText("Login*:");

        jLabel4.setText("Senha*:");

        btnNovoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/new.png"))); // NOI18N
        btnNovoUser.setText("Novo");
        btnNovoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoUserActionPerformed(evt);
            }
        });

        btnEditarUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/editar.png"))); // NOI18N
        btnEditarUser.setText("Editar");
        btnEditarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarUserActionPerformed(evt);
            }
        });

        btnExcluirUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/delete.png"))); // NOI18N
        btnExcluirUser.setText("Excluir");
        btnExcluirUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirUserActionPerformed(evt);
            }
        });

        btnCancelarUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/cancel.png"))); // NOI18N
        btnCancelarUser.setText("Resetar");
        btnCancelarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarUserActionPerformed(evt);
            }
        });

        btnSalvarUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/save.png"))); // NOI18N
        btnSalvarUser.setText("Salvar");
        btnSalvarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarUserActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel5.setText("Campos marcados com * são obrigatórios.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodUser)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 16, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNovoUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvarUser))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoUser)
                    .addComponent(btnEditarUser)
                    .addComponent(btnExcluirUser)
                    .addComponent(btnCancelarUser)
                    .addComponent(btnSalvarUser))
                .addGap(11, 11, 11)
                .addComponent(jLabel5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarUserActionPerformed
        // TODO add your handling code here:
        if (this.txtNameUser.getText().equals("") || this.txtLogin.getText().equals("") || this.txtSenha.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Favor prenncher os campos obrigatórios!", "ERRO", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                this.modelUsuario.setId(Integer.parseInt(this.txtCodUser.getText()));
            } catch (NumberFormatException e) {

            }
            this.modelUsuario.setName(this.txtNameUser.getText());
            this.modelUsuario.setLogin(this.txtLogin.getText());
            this.modelUsuario.setSenha(this.txtSenha.getText());
            if (this.salvarAlterar.equals("salvar")) {
                if (this.controllerUsuario.salvarUserController(this.modelUsuario) > 0) {
                    JOptionPane.showMessageDialog(this, "Usuário cadastrado com sucesso!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                    this.carregarUsuarios();
                    this.limparCampo();
                    this.habilitarDesabilitarCampo(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao cadastrar o usuário!", "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                if (this.controllerUsuario.atualizarUserController(this.modelUsuario)) {
                    JOptionPane.showMessageDialog(this, "Usuário atualizado com sucesso!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                    this.carregarUsuarios();
                    this.limparCampo();
                    this.habilitarDesabilitarCampo(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao atualizar o usuário!", "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnSalvarUserActionPerformed

    private void btnExcluirUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirUserActionPerformed
        // TODO add your handling code here:
        int linha = this.tbUser.getSelectedRow();

        try {
            int codUsuario = (int) this.tbUser.getValueAt(linha, 0);
            int result = JOptionPane.showConfirmDialog(this, "Tem certeza que dejesa excluir?", "ATENÇÃO", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (result == JOptionPane.YES_OPTION) {
                if (this.controllerUsuario.excluirUserController(codUsuario)) {
                    JOptionPane.showMessageDialog(this, "Usuário excluido com sucesso!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                    this.carregarUsuarios();
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao excluir o usuário!", "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Código inválido ou nenhum registro selecionado.", "ERRO", JOptionPane.ERROR_MESSAGE);
            this.habilitarDesabilitarCampo(false);
        }

    }//GEN-LAST:event_btnExcluirUserActionPerformed

    private void btnEditarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarUserActionPerformed
        // TODO add your handling code here:
        int linha = this.tbUser.getSelectedRow();
        this.salvarAlterar = "alterar";
        try {
            int codUser = (int) this.tbUser.getValueAt(linha, 0);

            this.modelUsuario = this.controllerUsuario.getUserController(codUser);
            this.txtCodUser.setText(String.valueOf(this.modelUsuario.getId()));
            this.txtNameUser.setText(this.modelUsuario.getName());
            this.txtLogin.setText(this.modelUsuario.getLogin());
            this.txtSenha.setText(this.modelUsuario.getSenha());
            this.habilitarDesabilitarCampo(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Código inválido ou nenhum registro selecionado.", "ERRO", JOptionPane.ERROR_MESSAGE);
            this.habilitarDesabilitarCampo(false);
        }
    }//GEN-LAST:event_btnEditarUserActionPerformed

    private void btnNovoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoUserActionPerformed
        // TODO add your handling code here:
        this.salvarAlterar = "salvar";
        this.habilitarDesabilitarCampo(true);
        this.limparCampo();
    }//GEN-LAST:event_btnNovoUserActionPerformed

    private void btnCancelarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarUserActionPerformed
        // TODO add your handling code here:
        this.habilitarDesabilitarCampo(false);
        this.limparCampo();
    }//GEN-LAST:event_btnCancelarUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewUser().setVisible(true);
            }
        });
    }

    private void carregarUsuarios() {
        this.listaModelUsuario = this.controllerUsuario.getListaUserController();
        DefaultTableModel modelo = (DefaultTableModel) this.tbUser.getModel();
        modelo.setNumRows(0);

        int cont = this.listaModelUsuario.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                this.listaModelUsuario.get(i).getId(),
                this.listaModelUsuario.get(i).getName(),
                this.listaModelUsuario.get(i).getLogin()
            });
        }
    }

    private void habilitarDesabilitarCampo(boolean condicao) {
        this.txtNameUser.setEnabled(condicao);
        this.txtLogin.setEnabled(condicao);
        this.txtSenha.setEnabled(condicao);
        this.btnSalvarUser.setEnabled(condicao);
        this.btnSalvarUser.setEnabled(condicao);
    }

    private void limparCampo() {
        this.txtCodUser.setText("");
        this.txtNameUser.setText("");
        this.txtLogin.setText("");
        this.txtSenha.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarUser;
    private javax.swing.JButton btnEditarUser;
    private javax.swing.JButton btnExcluirUser;
    private javax.swing.JButton btnNovoUser;
    private javax.swing.JButton btnSalvarUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbUser;
    private javax.swing.JTextField txtCodUser;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNameUser;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
