/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerVenda;
import controller.ControllerVendaProduto;
import controller.ProdutoController;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelProduto;
import model.ModelSessionUser;
import model.ModelVenda;
import model.ModelVendaProduto;
import sun.util.logging.PlatformLogger;
import util.BLDatas;

/**
 *
 * @author Vitor
 */
public class ViewPDV extends javax.swing.JFrame {

    private ViewPagamentoPDV viewPagamentoPDV;
    int qtd;
    ModelProduto modelProduto = new ModelProduto();
    ProdutoController controllerProduto = new ProdutoController();
    ArrayList<ModelProduto> listaModelProduto = new ArrayList<>();

    ModelVenda modelVenda = new ModelVenda();
    ControllerVenda controllerVenda = new ControllerVenda();

    ModelVendaProduto modelVendaProduto = new ModelVendaProduto();
    ControllerVendaProduto controllerVendaProduto = new ControllerVendaProduto();
    ArrayList<ModelVendaProduto> listaModelVendaProduto = new ArrayList<>();

    ModelSessionUser modelSessionUser = new ModelSessionUser();

    BLDatas bLDatas = new BLDatas();

    /**
     * Creates new form ViewPDV
     */
    public ViewPDV() {
        initComponents();
        setLocationRelativeTo(null);
        this.setOp();
        this.viewPagamentoPDV = new ViewPagamentoPDV(this, true);
        this.jTitleProdutoPDV.setText("CAIXA FECHADO");
        this.txtBarraCod.setEnabled(false);
        this.limparCampo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTitleProdutoPDV = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jValorUniPDV = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSubTotalPDV = new javax.swing.JTextField();
        jValorTotalPDV = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jQtdPDV = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jOpPDV = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPDV = new javax.swing.JTable();
        txtBarraCod = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jExcluirPDV = new javax.swing.JMenuItem();
        jPesquisarPDV = new javax.swing.JMenuItem();
        jMenuFinalizar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VPSoft - PDV");
        setBackground(new java.awt.Color(153, 153, 255));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jTitleProdutoPDV.setEditable(false);
        jTitleProdutoPDV.setBackground(new java.awt.Color(51, 51, 255));
        jTitleProdutoPDV.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTitleProdutoPDV.setForeground(new java.awt.Color(255, 255, 255));
        jTitleProdutoPDV.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTitleProdutoPDV.setText("Teste");
        jTitleProdutoPDV.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTitleProdutoPDV)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTitleProdutoPDV, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jPanel4.setBackground(new java.awt.Color(51, 51, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Valor Unit.");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Subtotal");

        jValorUniPDV.setEditable(false);
        jValorUniPDV.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jValorUniPDV.setEnabled(false);
        jValorUniPDV.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TOTAL");

        txtSubTotalPDV.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtSubTotalPDV.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSubTotalPDV.setEnabled(false);

        jValorTotalPDV.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jValorTotalPDV.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jValorTotalPDV.setEnabled(false);
        jValorTotalPDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValorTotalPDVActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Quantidade");

        jQtdPDV.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jQtdPDV.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jQtdPDV.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSubTotalPDV)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9))
                                .addGap(0, 301, Short.MAX_VALUE))
                            .addComponent(jQtdPDV)
                            .addComponent(jValorUniPDV))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jValorTotalPDV, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(159, 159, 159))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jValorUniPDV, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jQtdPDV, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSubTotalPDV, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jValorTotalPDV, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CAIXA:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("OPERADOR:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("PADRÃO");

        jOpPDV.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jOpPDV.setText("jLabel4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jOpPDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jOpPDV))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        tbPDV.setBackground(new java.awt.Color(153, 153, 255));
        tbPDV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbPDV.setForeground(new java.awt.Color(255, 255, 255));
        tbPDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Código", "Produto", "Qtd.", "Valor Unit.", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPDV.setEnabled(false);
        jScrollPane1.setViewportView(tbPDV);
        if (tbPDV.getColumnModel().getColumnCount() > 0) {
            tbPDV.getColumnModel().getColumn(0).setPreferredWidth(40);
            tbPDV.getColumnModel().getColumn(1).setPreferredWidth(40);
            tbPDV.getColumnModel().getColumn(2).setPreferredWidth(300);
        }

        txtBarraCod.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBarraCod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBarraCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBarraCodKeyReleased(evt);
            }
        });

        jMenuBar1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jMenu1.setForeground(new java.awt.Color(102, 102, 255));
        jMenu1.setText("ATALHOS");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        jMenuItem1.setText("Caixa");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jExcluirPDV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jExcluirPDV.setText("Excluir");
        jExcluirPDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExcluirPDVActionPerformed(evt);
            }
        });
        jMenu1.add(jExcluirPDV);

        jPesquisarPDV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jPesquisarPDV.setText("Pesquisar");
        jMenu1.add(jPesquisarPDV);

        jMenuFinalizar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuFinalizar.setText("Finalizar");
        jMenuFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFinalizarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuFinalizar);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(102, 102, 255));
        jMenu2.setText("OPÇÕES");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        jMenuItem4.setText("Sair");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
                    .addComponent(txtBarraCod))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBarraCod, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFinalizarActionPerformed
        // TODO add your handling code here:
        try {
            this.viewPagamentoPDV = new ViewPagamentoPDV(this, true);
            this.viewPagamentoPDV.setValorTotal(Float.parseFloat(this.txtSubTotalPDV.getText().replaceAll(",", ".")));
            this.viewPagamentoPDV.setTextValorTotal();
            this.viewPagamentoPDV.setVisible(true);

            this.jValorTotalPDV.setText(String.valueOf(this.viewPagamentoPDV.getValorTotal()).format("%.2f", this.viewPagamentoPDV.getValorTotal()));
            if (this.viewPagamentoPDV.isFinalizar()) {
                this.salvarVenda();
            } else {
                JOptionPane.showMessageDialog(this, "Venda cancelada!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                this.jTitleProdutoPDV.setText("CAIXA OCUPADO");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Insira produto(s) para finalizar a venda", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jMenuFinalizarActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jExcluirPDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExcluirPDVActionPerformed
        // TODO add your handling code here:
        int qtdLinha = this.tbPDV.getRowCount();
        if (qtdLinha < 1) {
            JOptionPane.showMessageDialog(this, "Não há item(s) para excluir.", "ERRO", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                DefaultTableModel modelo = (DefaultTableModel) this.tbPDV.getModel();
                int linha = Integer.parseInt(JOptionPane.showInputDialog("Número do item a excluir."));
                modelo.removeRow(linha - 1);
                this.txtSubTotalPDV.setText(String.valueOf(this.somarValorTotal()).format("%.2f", this.somarValorTotal()));
                this.jValorUniPDV.setText("0,00");
                this.jQtdPDV.setText("0");
                this.jTitleProdutoPDV.setText("CAIXA OCUPADO");
                for (int i = 0; i < qtdLinha; i++) {
                    modelo.setValueAt(i + 1, i, 0);
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jExcluirPDVActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.jTitleProdutoPDV.setText("CAIXA LIVRE");
        this.limparCampo();
        this.txtBarraCod.setEnabled(true);
        this.txtBarraCod.requestFocus();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void txtBarraCodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBarraCodKeyReleased
        // TODO add your handling code here:
        this.inserirProduto(evt);
    }//GEN-LAST:event_txtBarraCodKeyReleased

    private void jValorTotalPDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValorTotalPDVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jValorTotalPDVActionPerformed

    private void salvarVenda() {
        int cont, codProduto = 0, codVenda = 0;

        this.modelVenda = new ModelVenda();
        this.modelVenda.setIdClient(50);
        try {
            this.modelVenda.setDataVenda(bLDatas.converterDataParaDateUS(new java.util.Date(System.currentTimeMillis())));
        } catch (Exception ex) {
            Logger.getLogger(ViewPDV.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.modelVenda.setTotal(Double.parseDouble(this.txtSubTotalPDV.getText().replaceAll(",", ".")));
        this.modelVenda.setVenDesconto(Double.parseDouble(String.valueOf(this.viewPagamentoPDV.getDesconto()).replaceAll(",", ".")));
        this.modelVenda.setValor(Double.parseDouble(String.valueOf(this.viewPagamentoPDV.getValorTotal()).replaceAll(",", ".")));

        cont = this.tbPDV.getRowCount();
        codVenda = this.controllerVenda.salvarVendaController(this.modelVenda);
        for (int i = 0; i < cont; i++) {
            codProduto = (int) this.tbPDV.getValueAt(i, 1);
            this.modelVendaProduto = new ModelVendaProduto();
            this.modelProduto = new ModelProduto();
            this.modelVendaProduto.setIdProduto(codProduto);
            this.modelVendaProduto.setIdVenda(codVenda);
            this.modelVendaProduto.setVenProValor((double) this.tbPDV.getValueAt(i, 4));
            this.modelVendaProduto.setVenProQtd(Integer.parseInt(this.tbPDV.getValueAt(i, 3).toString()));

            this.modelProduto.setId(codProduto);
            this.modelProduto.setEstoque(this.controllerProduto.retornaProdutoController(codProduto).getEstoque() - Integer.parseInt(this.tbPDV.getValueAt(i, 3).toString()));

            this.listaModelVendaProduto.add(this.modelVendaProduto);
            this.listaModelProduto.add(this.modelProduto);
        }

        if (this.controllerVendaProduto.salvarVendaProdutoController(this.listaModelVendaProduto)) {
            this.controllerProduto.alterarEstoqueProdutoController(this.listaModelProduto);
            this.jTitleProdutoPDV.setText("OBRIGADO E VOLTE SEMPRE! :)");
            JOptionPane.showMessageDialog(this, "Venda realizada com sucesso!");
            this.jTitleProdutoPDV.setText("CAIXAR LIVRE");
            this.limparCampo();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao adicionar produtos na venda!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void inserirProduto(java.awt.event.KeyEvent evt) {
        DefaultTableModel modelo = (DefaultTableModel) this.tbPDV.getModel();
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            try {
                this.modelProduto = this.controllerProduto.getCodigoBarraController(String.valueOf(Long.parseLong(this.txtBarraCod.getText())));
                this.jTitleProdutoPDV.setText(this.modelProduto.getName());
                qtd = Integer.parseInt(JOptionPane.showInputDialog("Informe a quantidade.", 1));
                modelo.addRow(new Object[]{
                    modelo.getRowCount() + 1,
                    this.modelProduto.getId(),
                    this.modelProduto.getName(),
                    qtd,
                    this.modelProduto.getPrice(),
                    qtd * this.modelProduto.getPrice()
                });
                this.jValorUniPDV.setText(String.valueOf(this.modelProduto.getPrice()).format("%.2f", this.modelProduto.getPrice()));
                this.jQtdPDV.setText(String.valueOf(qtd));
                this.txtSubTotalPDV.setText(String.valueOf(this.somarValorTotal()).format("%.2f", this.somarValorTotal()));
                this.txtBarraCod.setText("");
            } catch (Exception ex) {
            }
        }
    }

    private float somarValorTotal() {
        float soma = 0, valor = 0;
        int cont = this.tbPDV.getRowCount();

        for (int i = 0; i < cont; i++) {
            valor = Float.parseFloat(String.valueOf(this.tbPDV.getValueAt(i, 5)));
            soma += valor;
        }
        return soma;
    }

    private void limparCampo() {
        this.jValorUniPDV.setText("");
        this.jQtdPDV.setText("");
        this.txtSubTotalPDV.setText("");
        this.jValorTotalPDV.setText("");
        DefaultTableModel modelo = (DefaultTableModel) this.tbPDV.getModel();
        modelo.setRowCount(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPDV().setVisible(true);
            }
        });
    }

    private void setOp() {
        this.jOpPDV.setText(this.modelSessionUser.name);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jExcluirPDV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuFinalizar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JLabel jOpPDV;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JMenuItem jPesquisarPDV;
    private javax.swing.JTextField jQtdPDV;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTitleProdutoPDV;
    private javax.swing.JTextField jValorTotalPDV;
    private javax.swing.JFormattedTextField jValorUniPDV;
    private javax.swing.JTable tbPDV;
    private javax.swing.JTextField txtBarraCod;
    private javax.swing.JTextField txtSubTotalPDV;
    // End of variables declaration//GEN-END:variables
}
